[phases.setup]
only_include_files = ["package.json"]

[phases.install]
ONLY_INCLUDE_FILES = ["package.json", "package-lock.json"]

[phases.build]
cmds = ["npx prisma generate"]

[phases.start]
cmd = "node dist/index.js"
